### ISSUE TITLE
doesn't work now

### ISSUE THREAD

**Issue by firstway** [binarylu/leetcode-ext#18]
Error in response to storage.get: TypeError: Cannot read property '0' of null
    at upload_problem (chrome-extension://eomonjnamkjeclchgkdchpabkllmbofp/leetcode-github.js:335:37)
    at null.callback (chrome-extension://eomonjnamkjeclchgkdchpabkllmbofp/leetcode-github.js:49:9)
    at HTMLDocument.<anonymous> (chrome-extension://eomonjnamkjeclchgkdchpabkllmbofp/leetcode-github.js:29:25)
    at fire (chrome-extension://eomonjnamkjeclchgkdchpabkllmbofp/lib/jquery.js:3119:30)
    at Object.fireWith [as resolveWith](chrome-extension://eomonjnamkjeclchgkdchpabkllmbofp/lib/jquery.js:3231:7)
    at Function.ready (chrome-extension://eomonjnamkjeclchgkdchpabkllmbofp/lib/jquery.js:3443:13)
    at completed (chrome-extension://eomonjnamkjeclchgkdchpabkllmbofp/lib/jquery.js:3474:10)

**Comment by FutureKen** [comment]
Same here, can't commit the LC questions and answers to github repo now.

**Comment by TerryC78** [comment]
Same error message here, "Add quesiton" and "Add README.md" disappeared and code could not be pushed to Github.

**Comment by nathan-du** [comment]
same here

**Comment by binarylu** [comment]
Sorry it's long time since my last update, so it may not match new leetcode UI. I will update ASAP.

**Comment by zhaodelong** [comment]
Same here :)

**Comment by zhaodelong** [comment]
same here :)

**Comment by arsenejiang** [comment]
Same problem here. Can't commit to github.

**Comment by FutureKen** [comment]
Github commit function is really useful, it helped me review my codes conveniently. If possible, could you fix that first?

**Comment by Nicksxs** [comment]
could you teach me how to upgrade this plugin , it's really useful, thanks

**Comment by Nicksxs** [comment]
@binarylu

**Comment by binarylu** [comment]
@Nicksxs Sure, emailed to youl

**Comment by Windfarer** [comment]
Any updating plan for this project? Or this project has been deprecated? @binarylu
